### ISSUE TITLE
CONTRIBUTING.mdの追加

### ISSUE THREAD

**Issue by hrsano645** [hrsano645/vs-covid19#22]
コントリビュートの方針を追加します。

- どなたでも参加可能
  - 情報提供の手段
- 開発者向け
  - ブランチの種類
  - プルリクエストの方法

**Comment by Okochama** [comment]
プルリクの段取り、たたき台です。

1. githubでissueを立てる。Slackで共有。（Slackでの会話がきっかけで→issue化のパターンもあり）
2. issueでソースに手を入れ始める場合はAssignessで立候補表明。
3. hrsano645/vs-covid19:dev-shizuoka-custom から自分のリポジトリへpullして最新にする
4. 自分のリポジトリのdev-shizuoka-customでissueに関する機能追加ブランチを作成。名前はissue-対象番号とか
5. 機能追加ブランチで変更作業
6. 機能追加ブランチからhrsano645/vs-covid19:dev-shizuoka-customへプルリクを出す。

参考　https://github.com/tokyo-metropolitan-gov/covid19#ブランチルール）

**Comment by hrsano645** [comment]
ありがとうございます！そのまま作りましょうかね。

**Comment by Okochama** [comment]
じゃ私が #24 の修正について、上の2.以降の流れに沿ってやってみます。
その結果微調整した結果を、私がCONTRIBUTING.mdにまとめてみるって段取りでどうですか？

**Comment by hrsano645** [comment]
お願いします。今週ちょっとやっている余裕がなかったので😅

**Comment by hrsano645** [comment]
@Okochama  slackで進めていた、devブランチをやめて、本番+機能追加ブランチのみの運用に書き換えてみました。

参考
- https://codefornumazu.slack.com/archives/CVC7VJVEH/p1585055741026100?thread_ts=1584968631.013700&cid=CVC7VJVEH
-  https://codefornumazu.slack.com/archives/CVC7VJVEH/p1585056482027200?thread_ts=1584968631.013700&cid=CVC7VJVEH

---

> 1. githubでissueを立てる。Slackで共有。（Slackでの会話がきっかけで→issue化のパターンもあり）
> 2. issueでソースに手を入れ始める場合はAssignessで立候補表明。
> 3. hrsano645/vs-covid19:foo-shizuoka-custom から自分のリポジトリへpullして最新にする
> 4. 自分のリポジトリのfor-shizuoka-customでissueに関する機能追加ブランチを作成。名前はissue-対象番号とか
> 5. 機能追加ブランチで変更作業
> 6. 機能追加ブランチからhrsano645/vs-covid19:for-shizuoka-customへプルリクを出す。
> 
> netlifyのプルリクエストデプロイ機能で、プルリクエストの内容で一時的にデプロイ結果を見ること（デプロイプレビュー）ができます。ローカルでチェックする以外の方法として利用できます。
> 
> [Introducing Deploy Previews in Netlify | Netlify](https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/)
> 

---

**Comment by hrsano645** [comment]
それと、Slackでも何度か質問が来ている、情報提供の手段もこちらにまとめます。

貢献者リストはREADME.mdのほうがよさそう？

**Comment by Okochama** [comment]
貢献者リストは東京の対策サイトだと、「CONTRIBUTORS.md」ってファイルで貢献者リスト作っているようですね。
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/CONTRIBUTORS.md

表の様式はちょっとslackでも意見を聞いて、同じように別ファイルにしてREADME.mdやindex.htmlのフッターからリンクさせるでどうですかね

**Comment by Okochama** [comment]
こんな感じでどうでしょう。

----
# 貢献の仕方

このサイトは静岡県内のNPO、シビックテック団体、他個人の有志にて開発・運営しています。

***
## 支援情報を投稿するには

下記の情報収集フォームより情報をお寄せ下さい。  
https://forms.gle/ZXUhKnHA1pZiLnva8


投稿頂いた内容は運営メンバーで確認の上、公開用のシートに記入いたします。


***
## 開発に参加するには
+ for-shizuoka-custom  
静岡用の本番ブランチです。  
当初は開発ブランチが別にありましたが、netlifyのプルリクエストデプロイ機能で、プルリクエストの内容で一時的にデプロイ結果を見ること（デプロイプレビュー）ができるので、今後はこのブランチを使います。

+ master  
本家政府版の内容です。

### 修正の流れ
 1. githubでissueを立てる。すでにissueができている場合は2.に進んで下さい。
 2. issueに対して自分が修正する場合は、issueのコメントで立候補して、Assigneesに自分を設定して下さい。
 3. hrsano645/vs-covid19:for-shizuoka-custom の内容を自分のリポジトリへpullやmergeして最新にして下さい。
 4. **自分のリポジトリの**for-shizuoka-customからissueに関する機能追加・修正ブランチを作成して下さい。  
 ブランチ名はPRを受けた際に分かりやすいように、*issue-番号*　のように命名する番号はissue番号として下さい。
 5. 自分の機能追加・修正ブランチで修正作業して下さい。
 6. 機能追加・修正ブランチから、hrsano645/vs-covid19:for-shizuoka-customへPull Requestを発行して下さい。

**Comment by hrsano645** [comment]
@Okochama LGTMです！

**Comment by hrsano645** [comment]
> 貢献者リストは東京の対策サイトだと、「CONTRIBUTORS.md」ってファイルで貢献者リスト作っているようですね。
> https://github.com/tokyo-metropolitan-gov/covid19/blob/development/CONTRIBUTORS.md
> 
> 表の様式はちょっとslackでも意見を聞いて、同じように別ファイルにしてREADME.mdやindex.htmlのフッターからリンクさせるでどうですかね

そうですね。自分から聞いてみます。
自分としてはCfJのように個人名と団体名は一緒のほうが外側にも見てもらえるので良いと思ってます。
両者を乗せるのは希望すればでよいと思うので、個人名@Code for *** といった感じかな。

貢献者リストは別のissueにしておきますね。

**Comment by hrsano645** [comment]
#32 でマージしたのでこちらはクローズします
