### ISSUE TITLE
OGPタグの画像がFBでは適応されない状況の改善

### ISSUE THREAD

**Issue by hrsano645** [hrsano645/vs-covid19#24]
@Okochama さんよりSlackにて

![image (1)](https://user-images.githubusercontent.com/23502/77145189-2b903d80-6acb-11ea-800d-99b871d9a073.png)

現在の状況でも、正しくリポジトリ内の画像を通してくれないので検証して修正してみます。

**Comment by hrsano645** [comment]
ローカルでチェックする手段があるといいけど、ありますかね？

**Comment by Okochama** [comment]
自分のph-pagesで色々試してみました。

パスを絶対パスにしてみる　→　ダメ
ogp要素（og:type、og:title、og:url、og:description）を一通り設定してみる　→　ダメ

最終手段として使用するOGPの画像ファイル名自体を変更したら更新はされました。

**Comment by kazuomatz** [comment]
一応、絶対パスが正しいことになってるのだけど、適当にパラメータつけてもいいかもしれません。
```
<meta property="og:image" content="https://vs-covid19-shizuoka.netlify.com/vscovid19.png?dt=20200320"/>
```

とか

**Comment by Okochama** [comment]
パラメータ作戦もダメでした

**Comment by Okochama** [comment]
うそ、いけたかも！

**Comment by Okochama** [comment]
?dt=20200320 だとダメで、その後、?dt=202003202250と?dt=20200321 に連続で変えたどこかで更新されたっぽい。
タイミングしっかり見てなかったんで、?dt=20200320でもいけてたのかも
![image](https://user-images.githubusercontent.com/9268282/77170341-416b2600-6afe-11ea-8cea-f19ac73da5cb.png)

**Comment by hrsano645** [comment]
パラメーターで行ける理由って何ですかね😅
それともnetlify側の問題なのかが気になる。

**Comment by Okochama** [comment]
参照するファイルは同じだけどURLが変わったと判断して再取得してるのかもしれませんね

**Comment by kazuomatz** [comment]
そうです。キャッシュ回避の常套手段です。

**Comment by Okochama** [comment]
こちら僕の方で対応します。またimage以外に、この辺も一緒に追加します。
og:url
og:type
og:title
og:description
og:site_name

**Comment by hrsano645** [comment]
@Okochama ありがとうございます！

**Comment by hrsano645** [comment]
OGPタグの更新を行って、現状だとFBやTwitterでも静岡版のアイキャッチ画像が見れるようになりました。解決したということでクローズします。

https://github.com/hrsano645/vs-covid19/commit/d6e70f6852bfa85d4e0e316a9292f1988e3b88c5
