### ISSUE TITLE
README.mdを静岡版にカスタマイズ

### ISSUE THREAD

**Issue by Okochama** [hrsano645/vs-covid19#26]
README.mdがCfJ版のままなので、Githubを見た人が静岡版だと気づきにくい。
静岡版の内容に差し替えしたい。

**Comment by hrsano645** [comment]
静岡版としての変更はこのぐらいですかね

- 画像ファイルの差し替え
- 静岡版の明記
- コントリビュートの方法（これはCONTRIBUTE.mdへリンクすればよさそう？）

**Comment by Okochama** [comment]
こちら僕引き受けます。

**Comment by hrsano645** [comment]
@Okochama ありがとうございます！

**Comment by Okochama** [comment]
こんな感じでどうでしょう。

VS COVID-19 #民間支援情報ナビ For 静岡県版
====
政府の新型コロナウイルス感染症対策にまつわる企業等の支援サービス情報を集約したWebサイト[VS COVID-19 #民間支援情報ナビ](https://vscovid19.code4japan.org/)を元に、NPO、シビックテック団体、個人有志などで作成した、静岡県内の支援情報のまとめサイトです。

https://vs-covid19-shizuoka.netlify.com/  
<img src=https://vs-covid19-shizuoka.netlify.com/vscovid19.png style='width:100%'>  

QRコード  
<img src="https://chart.apis.google.com/chart?chs=140x140&cht=qr&chl=https%3A%2F%2Fvs-covid19-shizuoka.netlify.com%2F">

## データについて
Data: [CC0](https://creativecommons.jp/sciencecommons/aboutcc0/) [企業などによる支援一覧 静岡県版](https://docs.google.com/spreadsheets/d/1GuGZIv8ptMl9-4FDDN7GQEAYhMQptpMRrEBP9FXcQSQ/edit?usp=sharing/)  
支援情報のご提供は[こちら](https://forms.gle/ZXUhKnHA1pZiLnva8)までお寄せ下さい。

## 補足情報
* 静岡県内のNPO、CivicTech団体等有志により収集した企業等による支援情報を基に整理したものです。支援サービスをすべて網羅しているわけではありません。
* 空欄は公開情報に明確に情報が記載されていないため空欄にしており、その内容がないというわけではありません。
* サービスの問い合わせ等は直接支援企業にお問い合わせ下さい。
* 推奨ブラウザは、Chrome/Safariの最新版です。ブラウザによっては、動作しないことがあります。
* 政府版「#民間支援情報ナビ」プロジェクトについては右のリンクを参照して下さい。（[経産省 ニュースリリース](https://www.meti.go.jp/press/2019/03/20200309004/20200309004.html)、[総務省 広報・報道](https://www.soumu.go.jp/menu_news/s-news/01ryutsu02_02000267.html)）

----
## 貢献の仕方
[CONTRIBUTING.md](CONTRIBUTING.md)を参照してください。

## 貢献者リスト
整理中

## ライセンス
[Apache-2.0](https://github.com/hrsano645/vs-covid19/blob/for-shizuoka-custom/LICENSE)

### 静岡県版サイト作成
[CC BY](https://creativecommons.org/licenses/by/4.0/deed.ja)　[Hiroshi sano](https://twitter.com/hrs_sano645) （[src on github](https://github.com/hrsano645/vs-covid19/tree/for-shizuoka-custom)）  

### 政府版オリジナル  
App：[CC BY](https://creativecommons.org/licenses/by/4.0/deed.ja) [Code for Japan](https://www.code4japan.org/) ([@taisukef](https://twitter.com/taisukef))  ([src on github](https://github.com/codeforjapan/vs-covid19)  )  
Design: [CC BY](https://creativecommons.org/licenses/by/4.0/deed.ja) [HOWMORI](https://howmori.org/) ([Takya Yamagata](https://twitter.com/howmori))

**Comment by hrsano645** [comment]
素晴らしいです！そのままプルリク出してもらえれればＯＫです！
