### ISSUE TITLE
検索方法のUI改善

### ISSUE THREAD

**Issue by Okochama** [hrsano645/vs-covid19#27]
検索方法のユーザインタフェイスを見直す。
関連issue　#4 、#25 
地域、キーワード、個人向け・企業向けで絞り込み　など

**Comment by hrsano645** [comment]
こっちに書いたほうが良かったｗ #25 から転記します


> 今、公式の最新masterに大きな改変が入ってるので、そちらを取り込んでから作業したほうがよさそうです。
> 
> [codeforjapan@aa382cb](https://github.com/codeforjapan/vs-covid19/commit/aa382cbaed3264125a71c85163e43d700ef6282d)
> 
> 地域の分け方については、全域を4部で分ける方法か、すべての市町群をプルダウンメニューで出すかが今のところの候補だと思います。
> 
> ちょっと蛇足ですが、地域検索をひとまず作れたら、検索のフォーム内にも、地域指定したらちゃんと地域で出せるようにしようと思ってます。
> 検索フォームを動的にいろいろやるのはちょっと面倒ですが、URLで検索結果を共有したいときに、地域もURLに混ぜれた方がいいかなと考えてます。方法論的にはこちらのコメントをベースにしようかと。
> 
> [#4 (comment)](https://github.com/hrsano645/vs-covid19/issues/4#issuecomment-599024939)

**Comment by hrsano645** [comment]
本家（#29）を取り込んでから作業するか、先に地域選択できるようにするかですが、本家のコードを取り込む作業をしてからやってみます。

どちらからやっても結局本家のコードを取り込むことに変わりないですし。

**Comment by hrsano645** [comment]
地域検索のプルダウンメニュー作りました。イメージはこんな感じ。
![image](https://user-images.githubusercontent.com/23502/79124234-dcda7880-7dd6-11ea-9551-9f7f16b138d7.png)

作業中のブランチはこちら。まだちゃんと動いていないです。選択してもリロード（show関数）が動いてくれないです。。
https://github.com/hrsano645/vs-covid19/tree/issue-27_add_local_selection

今は、全域、西武、中部、東部、伊豆で分けています。ただデータもこの5つで分けられているものではないので、市町群にするかはまた相談ですね。

**Comment by hrsano645** [comment]
> 今は、全域、西武、中部、東部、伊豆で分けています。ただデータもこの5つで分けられているものではないので、市町群にするかはまた相談ですね。

この部分すっかり忘れてましたが、キーワードに地域分けを入れておく必要がありましたね😅
#41 にもこの話を入れておく必要ありそう。

**Comment by furipon308** [comment]
IssueとPull Requestのどちらにコメントするか迷いましたが、実装ではなく仕様に関することなのでこちらにコメントします。
「全域」の定義に「①抽出条件として地域指定をしない」「②対象地域が県内全域の支援」という2つの意味が混在しているように思います。個人的には「全域」という単語から想像するのは②の方ですが、人によっては①を連想するかもしれません。

・対応案1
挙動は今と同じ(①)とし、選択肢の表現を「指定なし」のように明確に①と分かるような言葉にする。

・対応案2
「県内全域」「指定なし」の2つの選択肢を用意し、それぞれの挙動をさせる。

いかがでしょうか？

**Comment by Okochama** [comment]
僕も「②対象地域が県内全域の支援」の感覚に近いです。

対象地域のデータは「キーワード」に含めるのがいいのか、「対象地域」みたいな列追加して「中部,西部」みたいに列挙するのがいいのか考え所かなと思います。

**Comment by hrsano645** [comment]
@furipon308 @Okochama「全域」という言葉で確かに悩んでましたが、言葉的に全域の定義は自分としても②になると思ってます。ただ実装は①にしています。

地域については、どの対象までが対象なのかが問題で、支援情報によっては3つぐらいあると思ってます。

- 地域限定（西部中部東部伊豆, 市区町村）
- 全国に向けている: 通販系やネット経由のサービス
- 特に地域を定義しない:明記がないもの

「全国に向けている」パターンは `全国` を一つ入れて、データ側で定義してもよいと思います。
「特に地域の定義しない」パターンは、データ側で定義する手段が今のところはないです。

二つのパターンを考慮すると対応策は1になるかと思ってます。全国を一つ入れてもよいのですが、現状は指定なしと区別つけづらいですね。

**Comment by hrsano645** [comment]
それと今後は、特定の地域（エリア）限定か、そうでないかの情報もあってもよいかもしれません。

**Comment by furipon308** [comment]
利用者の視点で考えてみました。
恐らく、「自分の住んでいる地域で受けられる支援」を探すというのが最も一般的な絞り込みの目的ではないかと思います。その場合、仮に「中部」に住んでいると仮定すると、表示してほしい情報は「中部限定」「県下全域対象」「全国対象」の全てになります。逆に「西部限定」「東部限定」「伊豆限定」は除外してほしいはずです。(静岡県外限定はそもそも登録されていない前提)

そう考えると、
- 「指定なし」「西部」「中部」「東部」「伊豆」の5つの選択肢を用意
- 「指定なし」を選択した場合は絞り込みせずに全件表示
- 「指定なし」以外を指定をした場合は当該地域限定＋当該地域を包含する上位の地域(県内全域、全国等)を抽出

とするのが良いように思いますが、どうでしょうか？

「包含する上位の地域」を抽出する実装をどうするか考えどころですが、「全国」や「静岡県」といった統一キーワードを決めておいて、「中部」or「静岡県」or「全国」のようにすれば何とかなると思います。

なお、「地域を定義していない(明記がない)」を地域指定に含めるかどうかは意見が分かれるかと思います。(今回のケースであれば私は含めていいと考えます)

**Comment by hrsano645** [comment]
> * 「指定なし」「西部」「中部」「東部」「伊豆」の5つの選択肢を用意
> * 「指定なし」を選択した場合は絞り込みせずに全件表示
> * 「指定なし」以外を指定をした場合は当該地域限定＋当該地域を包含する上位の地域(県内全域、全国等)を抽出
> 
> とするのが良いように思いますが、どうでしょうか？

@furipon308  最後の指定なし以外選択の包括案はよいと思います。データとしては、指定したもの以外の地域を外して、それ以外を以外をリストアップする形になるので、すでに地域のリストがあればそれほど苦労しないと思います。できたらプルリクのブランチ更新します。

**Comment by hrsano645** [comment]
@furipon308 さんとのslackでのやり取り例をまとめておきます。

実装した状態で情報一覧を見ると、地域不明なものが違和感出てしまう。せっかく地域で絞っているのに、地域不明となるが実は地域がわかる情報が入っている（例:「中部」で絞り込んでいるのに下田の飲食店の情報が表示される）
https://codefornumazu.slack.com/archives/CVC7VJVEH/p1587047478176200?thread_ts=1586786722.157200&cid=CVC7VJVEH

地域がわかるものについては、地域情報をまず入れることにして（データ側を手入れ）、どうしても情報に載せられない場合は、地域選択の一覧に、`地域不明`の項目を追加する。

また副次的ですが、全国向けの情報も2020-04-17時点で18件登録されているので、`全国`という項目も追加してみます。
> https://codefornumazu.slack.com/archives/CVC7VJVEH/p1587083694176400?thread_ts=1586786722.157200&cid=CVC7VJVEH
