### ISSUE TITLE
支援の終了がある情報の表示を終了したとわかりやすくする

### ISSUE THREAD

**Issue by hrsano645** [hrsano645/vs-covid19#31]
Slackより

https://codefornumazu.slack.com/archives/CVC7VJVEH/p1585463307012500

https://codefornumazu.slack.com/archives/CVC7VJVEH/p1585465688018100

Slackをまとめると、支援が終了したときに丸ごとデータを消すと、存在したにもかかわらず消えてしまってる状態に見えてしまうので、それよりは履歴として残すけど終了したことを見せれた方が良さそう。

**Comment by hrsano645** [comment]
とりあえず作ってみました。期間備考の`終了`の文字列を検索した結果を条件として、置き換えてるぐらいにしています。

![image](https://user-images.githubusercontent.com/23502/77850672-1031da80-720f-11ea-8b2c-5157b3d9d963.png)

**Comment by Okochama** [comment]
【現在は終了している可能性あります】でも終了扱いになるので、悩ましいですね。

終了断言できるか微妙なのは【現在は終わっている可能性あります】にして判定から避けます？

**Comment by hrsano645** [comment]
あー確かに。そこはデータを最新にするべきか悩ましいですね。

終了判断でほかに使える項目は、終了日ですかね。現在日時と照らしわせる感じです。

**Comment by hrsano645** [comment]
> 終了断言できるか微妙なのは【現在は終わっている可能性あります】にして判定から避けます？

その形で避けることは出来ます。ひとまずデータ側の言葉で調整しましょうか？
確認用にPR出しておきます。

**Comment by Okochama** [comment]
slackのコメントと重複しますが、**【提供終了】**　で判定もありかと思いました。

**Comment by hrsano645** [comment]
文字だけだと判断しにくいのでその形でよさそうですね。 更新しておきます。
