### ISSUE TITLE
地域検索の方法を検討する

### ISSUE THREAD

**Issue by hrsano645** [hrsano645/vs-covid19#4]
Slackにて提案

https://codefornumazu.slack.com/archives/CVC7VJVEH/p1584108508016100

> SHINJO 昨日 23:08
> 登録数が増えてきたら、東部、中部、西部、伊豆みたいに分けられたほうがいいかもしれないですね。

**Comment by hrsano645** [comment]
https://codefornumazu.slack.com/archives/CVC7VJVEH/p1584153419026400?thread_ts=1584108508.016100&cid=CVC7VJVEH

> 検索はすべての項目に対して、部分一致で検索してるっぽいので、何かしら地域名が入ってると検索が当たりますね。
> 検索窓の次にタグがありますが、このサービスではトップタグとよばれているもので、クリック/タップすると検索窓に自動的に入力されます。今は分野の項目をタグとして出してるようです。
> ここに地域名（西部、中部、東部、伊豆）とか市町（沼津、富士、静岡、掛川、裾野）といったようにタグを並べてショートカットを作ってもよいかも。

**Comment by hrsano645** [comment]
地域一覧として、市町をリストアップすると、こちらだと思います。

http://www.pref.shizuoka.jp/link/citylink.html

タグとして並べると多くなりそう。

**Comment by hrsano645** [comment]
スマホから見た様子。各地域名をタグと同じデザインで並べるとこうなる。

![image](https://user-images.githubusercontent.com/23502/76677469-ea52e600-6611-11ea-97b6-52c326de001c.png)

さすがに見づらいので、以下でやってみるつもり。ほかにいいアイディアがあればほしいです。

**Comment by hrsano645** [comment]
今のところのアイディア

- プルダウンメニューで、地域限定にできるようにする
- プルダウンメニューには市町36の名称と全体が見れる”静岡県全域" を入れる
- 検索窓にはプルダウンメニュー上で選択した市町名が検索文字列最初に入る（プラス半角スペース）
- プルダウンメニューを変更したときに検索窓は市町名を入れ替えるようにする（文字列置き換える形で）
- プルダウンメニューで"静岡県全域"を選ぶと、検索窓に入っている冒頭の市町が消える（途中で入ってるかもしれないので、数文字のみを調べて置き換え）

市町名は動的に変わることはないので、jsonファイルをおいてそこから読み込むつもり。

**Comment by hrsano645** [comment]
https://codefornumazu.slack.com/archives/CVC7VJVEH/p1584172182053900

> nozomi  16:49
> 自治体タグ35は多いですね…３分類＋全国区ぐらいで分けると良いのでは。
> それとジャンルタグと一緒の形は見辛いですね…せめて自治体とジャンルのボタン色を変えてみましょうか

**Comment by hrsano645** [comment]
地域+ほかのキーワードをタグで入れるようにすると検討に時間がかかりそうなので、まずはシンプルに地域タグを押したら地域のみ、ジャンルタグを押したらジャンルのみにしておきます。

**Comment by Okochama** [comment]
こちらは #25 も含め、 #27 でまとめています

**Comment by hrsano645** [comment]
今、公式の最新masterに大きな改変が入ってるので、そちらを取り込んでから作業したほうがよさそうです。

https://github.com/codeforjapan/vs-covid19/commit/aa382cbaed3264125a71c85163e43d700ef6282d

地域の分け方については、全域を4部で分ける方法か、すべての市町群をプルダウンメニューで出すかが今のところの候補だと思います。


ちょっと蛇足ですが、地域検索をひとまず作れたら、検索のフォーム内にも、地域指定したらちゃんと地域で出せるようにしようと思ってます。
検索フォームを動的にいろいろやるのはちょっと面倒ですが、URLで検索結果を共有したいときに、地域もURLに混ぜれた方がいいかなと考えてます。方法論的にはこちらのコメントをベースにしようかと。

https://github.com/hrsano645/vs-covid19/issues/4#issuecomment-599024939

**Comment by hrsano645** [comment]
実装終わったので終了します。
