### ISSUE TITLE
政府版へのリンクを見やすいところに掲載する

### ISSUE THREAD

**Issue by hrsano645** [hrsano645/vs-covid19#40]
政府（本家）版と情報が違うため、政府版を知らない人向けにもリンクを乗せたほうが良い？と思ってどこかしらにリンクの追加を行います。

位置としてはちょうど赤枠の部分を想定してます。

![image](https://user-images.githubusercontent.com/23502/78519210-9f398680-77fd-11ea-9b00-5155fc8630bf.png)

**Comment by Okochama** [comment]
政府版のリンク以外に、下記のような文章も同じ辺りに注意書き入れましょうか。

既に提供終了していたり、サービスの内容に変更があっても反映できていない場合があります。サービスの問い合わせ等は直接支援企業にお問い合わせ下さい。

**Comment by hrsano645** [comment]
@Okochama その形で進めておきます。
