### ISSUE TITLE
支援情報データの編集方針もCONTRIBUTING.mdに入れる

### ISSUE THREAD

**Issue by hrsano645** [hrsano645/vs-covid19#41]
現在の支援情報データの編集方針を

今決まっているものを挙げておきます。

- 定期的に収集フォームに登録された情報を本番用データに登録する
- 見つけた情報については、過去の支援情報を元に記載する（特にガイドラインなどがなく、今後の課題です）
- 適時確認し、支援が終了している、延長している、同じ企業で別の支援情報があるか などを確認
  - 支援が終了している場合：情報は消さずに、`期間備考` に `【提供終了】` を追記する
  - 延長している: 該当する支援情報を修正
  - 同じ企業で別の支援情報がある: 別の支援情報として追加する

---

決めたほうがいいもの

- 追加のガイドライン

**Comment by hrsano645** [comment]
データ編集のキーワードに入れている、地域（全国,西部,中部,東部,伊豆）を入れるときの基準もほしいです。対象の地域のことを言うのか？、地域の企業のことか？ です。

https://github.com/hrsano645/vs-covid19/issues/27#issuecomment-612912352

**Comment by Okochama** [comment]
利用者視点で見れば、前者の方がしっくりくる気がしますね
