### ISSUE TITLE
提供終了した支援はリストの末尾に表示してはどうか

### ISSUE THREAD

**Issue by furipon308** [hrsano645/vs-covid19#42]
様々な支援を見てもらうという観点で支援をシャッフルして表示するのはいいと思いますが、無条件にシャッフルすると提供終了した支援が上の方に表示されてしまう場合があります。
提供終了したものはリストの末尾に集め、有効な支援が上の方に表示されるようにしてはどうでしょうか？（簡単にできそうなので私の方でやってみます）

**Comment by hrsano645** [comment]
提案もらったプルリクはマージしました（ありがとうございます！）
