### ISSUE TITLE
OGPタグの画像を静岡版に修正する

### ISSUE THREAD

**Issue by hrsano645** [hrsano645/vs-covid19#5]
静岡版のURLをSNSなどでシェアすると、OGPタグの設定で、全国版のイメージが現れる。

https://slack-files.com/T1CM55Y2V-FVCBBF3FF-9ddb34ce62

これだとわかりづらいので、修正して地域版の作成をします。

参照: https://codefornumazu.slack.com/archives/CVC7VJVEH/p1584098647008100

**Comment by IchikawaNozomi** [comment]
直しました。プルリクしました。

**Comment by hrsano645** [comment]
プルリク受けました！👍
https://github.com/hrsano645/vs-covid19/pull/7
